<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices  </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [185]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists



# Here the user is allowed to enter data in Matrix  A and B and if the criteria is not fulfilled then the result of "Not Possible" is displayed in the end 
def matrix_mul(A, B):
    
    D  = [[0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0]]
    
    D = []
    for i in range(R):
        matrix = []
        for j in range(Co):
            matrix.append(0)
        D.append(matrix)
    
    
    if len(A[1]) == len(B):
        for i in range(len(A)):
            for j in range(len(B[1])):
                for k in range(len(B)):
                    D[i][j] += A[i][k] * B[k][j]
                    
        for i in D:
            print(i)
    
    
    
    else:
        print("Not Possible")

R = int(input("Enter the number of rows: "))
C = int(input("Enter the number of columns: "))

A = []
for i in range(R):
    matrix = []
    for j in range(C):
        matrix.append(int(input()))
    A.append(matrix)
    
print(A)


Ro = int(input("Enter the number of rows: "))
Co = int(input("Enter the number of columns: "))

B = []
for i in range(Ro):
    matrix = []
    for j in range(Co):
        matrix.append(int(input()))
    B.append(matrix)
print(B)    
print("\n")

matrix_mul(A,B) 


# Here I have given the user right to choose rows and columns of the matrices to multiply




Enter the number of rows: 2
Enter the number of columns: 2
4
6
2
8
[[4, 6], [2, 8]]
Enter the number of rows: 2
Enter the number of columns: 2
14
5
15
87
[[14, 5], [15, 87]]


[146, 542]
[148, 706]


# <h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements </h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [44]:
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# Here I have used random.uniform function 
# References - https://docs.python.org/3/library/random.html

def pick_a_number_from_list(A):
    
    w = []
    for i in A:
        w.append(i/sum(A))
    
    somi=0
    cum_sum=[]
    for i in range(len(A)):
        somi = somi + A[i]
        cum_sum.append(somi)
    
    #selected_random_number = random.choices(A,w,k=1)
    
    selected_random_number = int(random.uniform(0,somi))
    
    for index in range(len(cum_sum)):
        if(selected_random_number >=cum_sum[index] and selected_random_number <cum_sum[index+1]):
            return A[index+1]
    
    return selected_random_number


def sampling_based_on_magnitude(): 
    
    fnl = dict()

    for i in range(1,500):
        selected_random_number = pick_a_number_from_list(A)
        #print(number)
        if selected_random_number not in fnl:
            fnl[selected_random_number] = 1
        else:
            fnl[selected_random_number] += 1
    
    
    inputs = []
    Frequency = []
    for K, V in fnl.items():
        inputs.append(K)
        Frequency.append(V)
        #print(K,"   ",V)
        
    hiy = sorted(inputs,reverse=True)
    bho = sorted(Frequency,reverse=True)
    
    #print(bho)
    
    new1 = ["Input List"]
    
    new1.extend(hiy)
    
    #print(new1)
    
    
    new2 = ["Frequency of This Number Selection"]
    
    new2.extend(bho)
    
    #print(new2)
    
    jun = zip(new1,new2)
    
    tron = list(jun)
    
    
    
    for gn in tron:
        print(gn[0],"                         ",gn[1])
    
    
A=[0, 5 ,27, 6, 13, 28, 100, 45, 10,79]
sampling_based_on_magnitude()

Input List                           Frequency of This Number Selection
100                           148
79                           141
45                           76
28                           44
27                           38
13                           19
10                           17
6                           10
5                           6


<h3> Q3: Replace the digits in the string with # </h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [29]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    
    num = re.sub(r'\D', "", String)  
    
    final = re.sub(r"[0-9]","#",num)
    
    return final # modified string which is after replacing the # with digits




String1 = "234"
print("Result after removing and replacing the string: ",replace_digits(String1))
String2 = "a2b3c4"
print("Result after removing and replacing the string: ",replace_digits(String2))
String3 = "abc"
print("Result after removing and replacing the string: ",replace_digits(String3))
String4 = "#2a$#b%c%561#"
print("Result after removing and replacing the string: ",replace_digits(String4))



Result after removing and replacing the string:  ###
Result after removing and replacing the string:  ###
Result after removing and replacing the string:  
Result after removing and replacing the string:  ####


<h3> Q4: Students marks dashboard </h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [30]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# Reference - https://stackoverflow.com/questions/1663807/how-to-iterate-through-two-lists-in-parallel


# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    #list1 = students.extend(marks)
    #print(students)
    
    Z = [x for y, x in sorted(zip(marks, students))]
    
    Op = sorted(marks)
    
    
    #print(Z,Op)

    studnam = Z[:4:-1]
    newmark = Op[:4:-1]
    for i,j in zip(studnam,newmark):
        print(i,j)
    print("\n")
    
    
    studname = Z[:5]
    lowmark = Op[:5]
    for i,j in zip(studname,lowmark):
        print(i,j)
    print("\n")
    
    
    
    
    Rank = []
    for j in range(len(Op)):
        Rank.append(j+1)
    #print(Rank)
    
    
    #Made my own rounding off function(myround)
    percentiles = []
    for i in range(2):
        h = int(input("Enter the percentile to calculate: "))
        def myround(b):
            nj = str(b)
            d = nj.split(".")
            test_list = [int(i) for i in d]
            if test_list[1] <= 5:
                return int(b)
            else:
                return round(b)
        percentile = myround((h/100)*len(Rank))
        
        #print(percentile)
        Val1 = Op[percentile-1]
        Val2 = Op[percentile]
        Avg = (Val1 + Val2)/2
        percentiles.append(Avg)
        
    new_percentiles = []
    for i in Op:
        if i > percentiles[0] and i < percentiles[1]:
            new_percentiles.append(i)
            
    #print(new_percentiles)
    
    c = zip(marks,students)
    
    u = []
    t = []
    for i in c:
        for j in new_percentiles:
            if j == i[0]:
                u.append(i[1])
                t.append(i[0])
            
    nh = zip(t,u)
    print("\n")
    x = sorted(tuple(nh))
    #print(x)
    for k in x:
        print(k[1],k[0])
    
    # write code for computing top least 5 students
    #least_5_students = # compute this
    # write code for computing top least 5 students
    #students_within_25_and_75 = # compute this
    
    #return top_5_students, least_5_students, students_within_25_and_75


#print(# those values)
students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(students, marks)

student8 98
student10 80
student2 78
student5 48
student7 47


student3 12
student4 14
student9 35
student6 43
student1 45


Enter the percentile to calculate: 25
Enter the percentile to calculate: 75


student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points </h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [149]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    
    pointdist = []
    closest_points_to_p = []
    for i in S:
        dist = (P[0]*i[0] + P[1]*i[1])/((math.sqrt(i[0]**2 + i[1]**2))*(math.sqrt(P[0]**2 + P[1]**2)))
        if dist > 0:
            closest_points_to_p.append(i)
        pointdist.append(dist)
        
    
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

for j in closest_points_to_p(S, P):
    print(j)


(6, -7)
(-5, -8)
(-1, -1)
(6, 0)
(1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [28]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# Here I have used "eval" function from math module
# Used the intuition of:   if ax +by + c > 0 for A(x1,y1) and if ax + by + c < 0 for B(x2,y2) then we can conclude that both points are on opposite side to line in comparison to each other.
def i_am_the_one(red,blue,line):
    sign_r = -1
    
    if eval(line.replace("x","*%s" % red[0][0]).replace("y", "*%s" % red[0][1])) > 0:
        sign_r = 1
        
    for pointred in red:
        if sign_r == 1 and eval(
                line.replace("x","*%s" % pointred[0]).replace("y", "*%s" % pointred[1])) < 0:
            return "NO"
        if sign_r == -1 and eval(
                line.replace("x","*%s" % pointred[0]).replace("y", "*%s" % pointred[1])) > 0:
            return "NO"
    
    sign_b = -1 * sign_r 
    
    for pointblue in blue:
        if sign_b == 1 and eval(
                line.replace("x","*%s" % pointblue[0]).replace("y", "*%s" % pointblue[1])) < 0:
            return "NO"
        if sign_b == -1 and eval(
                line.replace("x","*%s" % pointblue[0]).replace("y", "*%s" % pointblue[1])) > 0:
            return "NO"
    
    return "YES"
    

red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(red, blue, i)
    print(yes_or_no) 

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate </h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [16]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# I have not written a optimized code but is running correctly in which mutiple inputs can be taken other than given in question description.
# Please ignore the choice of variable name, took it in hurry.
# References -https://www.geeksforgeeks.org/python-custom-list-split/
def EqualSplit(S):
    string_split_done = S.split(",")
    replacement_of = [i if i!='_' else 0 for i in string_split_done]
    converted_tointerger = [int(ue) for ue in replacement_of]
    # Replaced "_" with 0 and then converted whole list into list of integer
    
    ni = 0
    for i in replacement_of:
        if i != 0:
            # Splitting the integer value into equal parts(length of "replacement_of")
            ni += float(int(i)/len(replacement_of))
        
    
    ko = []
    for j in replacement_of:
        ko.append(ni)
            
    uy = []
    for i in converted_tointerger:
        if i != 0:
            uy.append(i)
    # Splitting the integer value into equal parts when 1st and last value is present in list(length of "replacement_of")
    sur = int(sum(uy)/len(replacement_of))

    newk = []
    for i in converted_tointerger:
        newk.append(sur)
    
    return newk
        
        
        
def doublesplit(T):
    # Splitting
    tr = T.split(",")
    
    # Replacing and converting underscore and assigning it to new lists
    jny = [i if i!='_' else 0 for i in tr]
    hut = [int(ue) for ue in jny]
    
    # Getting the numbers and index of numbers that are not equal to zero
    index = []
    nums = []
    for i in jny:
        if i != 0:
            nums.append(int(i))

    for j in range(len(jny)):
        if jny[j] != 0:
            index.append(j)
    
    jo = [i+1 for i in index]

    #Splitting list into equal parts according to index list 
    res = [hut[i : j] for i, j in zip([0] + jo, jo + [None])]


    go = res[1].append(0)
    kp = res[2].append(0)

    fnl = []
    bot = 0
    for y in jny:
        if y != 0:
            bot = int(int(y)/(index[0]+1))
            #print(bot)
            fnl.append(bot)
            break
        
    fnl1 = []       
    for i in range(index[0]+1):
        fnl1.append(bot)

    # Appending 2nd list
    lstr = []
    valu = 0
    for i in res[1]:
        if i > 0:
            valu = int((i + bot)/len(res[1]))
            lstr.append(valu)
        
    fnl2 = []
    for  j in res[1]:
        fnl2.append(valu)
    
    # Appending 3rd list
    fnl3 = []
    for  j in res[2]:
        fnl3.append(int(valu/len(res[2])))
    
    #Adding all three lists with already appended values
    final = fnl1[:index[0]] + fnl2[:index[1]-2] + fnl3

    return final
        
    
    
    
S=  "40,_,_,_,60"
E = "80,_,_,_,_"
F = "_,_,_,24"
T =  "_,_,30,_,_,_,50,_,_"

print(EqualSplit(S))
print(EqualSplit(E))
print(EqualSplit(F))
print(doublesplit(T))


[20, 20, 20, 20, 20]
[16, 16, 16, 16, 16]
[6, 6, 6, 6]
[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate </h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [46]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# It may look like some part is hardcoded but eventually I had to take those extra variables for calculating Conditional Probability
# But the functionality is 100% Working
def compute_conditional_probabilites(A):
    
    counts1 = 0
    for i in A:
        if i[1] == "S1":
            counts1 += 1
    #print(counts1)
    
    counts2 = 0
    for j in A:
        if j[1] == "S2":
            counts2 += 1
    #print(counts2)
    
    counts3 = 0
    for k in A:
        if k[1] == "S3":
            counts3 += 1
    #print(counts3)
    
    countf1s1 = 0
    countf1s2 = 0
    countf1s3 = 0
    for i in A:
        if i[0] == "F1" and i[1] == "S1":
            countf1s1 += 1
        elif i[0] == "F1" and i[1] == "S2":
            countf1s2 += 1
        elif i[0] == "F1" and i[1] == "S3":
            countf1s3 += 1
    
    countf2s1 = 0
    countf2s2 = 0
    countf2s3 = 0
    for i in A:
        if i[0] == "F2" and i[1] == "S1":
            countf2s1 += 1
        elif i[0] == "F2" and i[1] == "S2":
            countf2s2 += 1
        elif i[0] == "F2" and i[1] == "S3":
            countf2s3 += 1
    
    countf3s1 = 0
    countf3s2 = 0
    countf3s3 = 0
    for i in A:
        if i[0] == "F3" and i[1] == "S1":
            countf3s1 += 1
        elif i[0] == "F3" and i[1] == "S2":
            countf3s2 += 1
        elif i[0] == "F3" and i[1] == "S3":
            countf3s3 += 1
    
    countf4s1 = 0
    countf4s2 = 0
    countf4s3 = 0
    for i in A:
        if i[0] == "F4" and i[1] == "S1":
            countf4s1 += 1
        elif i[0] == "F4" and i[1] == "S2":
            countf4s2 += 1
        elif i[0] == "F4" and i[1] == "S3":
            countf4s3 += 1
    
    countf5s1 = 0
    countf5s2 = 0
    countf5s3 = 0
    for i in A:
        if i[0] == "F5" and i[1] == "S1":
            countf5s1 += 1
        elif i[0] == "F5" and i[1] == "S2":
            countf5s2 += 1
        elif i[0] == "F5" and i[1] == "S3":
            countf5s3 += 1
    
    
    
    print("P(F=F1|S==S1)=",countf1s1,"/",counts1,"     P(F=F1|S==S2)=",countf1s2,"/",counts2,"     P(F=F1|S==S3)=",countf1s3,"/",counts3)
    print("P(F=F2|S==S1)=",countf2s1,"/",counts1,"     P(F=F2|S==S2)=",countf2s2,"/",counts2,"     P(F=F2|S==S3)=",countf2s3,"/",counts3)
    print("P(F=F3|S==S1)=",countf3s1,"/",counts1,"     P(F=F3|S==S2)=",countf3s2,"/",counts2,"     P(F=F3|S==S3)=",countf3s3,"/",counts3)
    print("P(F=F4|S==S1)=",countf4s1,"/",counts1,"     P(F=F4|S==S2)=",countf4s2,"/",counts2,"     P(F=F4|S==S3)=",countf4s3,"/",counts3)
    print("P(F=F5|S==S1)=",countf5s1,"/",counts1,"     P(F=F5|S==S2)=",countf5s2,"/",counts2,"     P(F=F5|S==S3)=",countf5s3,"/",counts3)
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S==S1)= 1 / 4      P(F=F1|S==S2)= 1 / 3      P(F=F1|S==S3)= 0 / 3
P(F=F2|S==S1)= 1 / 4      P(F=F2|S==S2)= 1 / 3      P(F=F2|S==S3)= 1 / 3
P(F=F3|S==S1)= 0 / 4      P(F=F3|S==S2)= 1 / 3      P(F=F3|S==S3)= 1 / 3
P(F=F4|S==S1)= 1 / 4      P(F=F4|S==S2)= 0 / 3      P(F=F4|S==S3)= 1 / 3
P(F=F5|S==S1)= 1 / 4      P(F=F5|S==S2)= 0 / 3      P(F=F5|S==S3)= 0 / 3


<h3> Q9: Given two sentances S1, S2 </h3> 
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [47]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    
    first = S1.split(" ")
    second = S2.split(" ")
    
    a = 0
    for i in range(len(first)):
        if first[i] == second[i]:
            a += 1
            
    j1 = set(first)
    j2 = set(second)
    
    b = list(j1 - j2)
    c = list(j2 - j1)
    
    return a,b,c



S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
for u in string_features(S1, S2):
    print(u)

7
['first', '5', 'F']
['3', 'S', 'second']


<h3> Q10: Given two sentances S1, S2 </h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [251]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    
    x = len(A)
    
    loss = 0
    for t in A:
        loss += (t[0]*(math.log10(t[1]))+((1-t[0])*(math.log10(1-t[1]))))
    
    print(loss/(-x))
                       
A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
compute_log_loss(A)


0.42430993457031635
